http: "127.0.0.1"
http_port: 8001
db_host: "127.0.0.1"
db_port: 5432
db_name: "srbolab_cpc"
db_user: "postgres"
db_password: "passw0rd"
domain: "http://127.0.0.1:8001"
root_path: "/home/wolf/Desktop/test/"
corporateIps:
  - "109.121.53.252"