host: "127.0.0.1"
port: 8000
dbHost: "127.0.0.1"
dbPort: 5432
dbName: "srbolab_cpc"
dbUser: "postgres"
dbPassword: "password"
domain: "http://127.0.0.1:8080"
corporateIps:
  - "127.0.0.1"
  - "127.0.0.2"